#!/usr/bin/env bash
set -euo pipefail

# One-time, per-MACHINE teardown: the inverse of bootstrap-openbao.sh.
# Stops + unregisters the machine-global pitchfork daemon (waiting until it
# has actually exited), then wipes the raft store / rendered config /
# secret files / tofu state. Raft snapshots under <state_dir>/snapshots/
# are KEPT -- that directory is the restore bundle (snap + seal.key +
# root.token, written together by `mise run local:openbao:snapshot`).
#
# GitOps role: one-time teardown. Not a reconcile-loop step.
#
# This is MACHINE-WIDE: every git worktree shares the one local OpenBao,
# so this wipes it for all of them. Confirm unless TOOLBOX_OPENBAO_RESET_YES=1.
#
# Test seams (bats): TOOLBOX_OPENBAO_STATE_DIR, TOOLBOX_OPENBAO_DAEMON,
# TOOLBOX_OPENBAO_LISTEN, TOOLBOX_OPENBAO_SUPERVISOR (pitchfork|none).

STATE_DIR="${TOOLBOX_OPENBAO_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/toolbox/openbao}"
DAEMON="${TOOLBOX_OPENBAO_DAEMON:-openbao}"
LISTEN="${TOOLBOX_OPENBAO_LISTEN:-127.0.0.1:8200}"
SUPERVISOR="${TOOLBOX_OPENBAO_SUPERVISOR:-pitchfork}"

if [ "${TOOLBOX_OPENBAO_RESET_YES:-}" != "1" ]; then
  printf 'Wipe the machine-global local OpenBao at %s (all worktrees)? [y/N] ' "$STATE_DIR"
  read -r reply
  case "$reply" in
  y | Y | yes | YES) ;;
  *)
    echo "Aborted."
    exit 0
    ;;
  esac
fi

pid=""
if [ "$SUPERVISOR" = "none" ]; then
  [ -f "$STATE_DIR/bao.pid" ] && pid="$(cat "$STATE_DIR/bao.pid")"
  [ -n "$pid" ] && kill "$pid" 2>/dev/null || true
else
  pid="$(pgrep -f "bao server -config=$STATE_DIR/openbao.hcl" | head -1 || true)"
  pitchfork stop "global/$DAEMON" 2>/dev/null || true
  pitchfork daemons remove --global "$DAEMON" 2>/dev/null || true
  # `daemons remove` drops it from config.toml but leaves a stopped entry
  # in `pitchfork list`; --daemon clears exactly that one (never a
  # machine-wide `pitchfork clean`).
  pitchfork clean --daemon "global/$DAEMON" 2>/dev/null || true
fi

# Wait for the daemon to actually exit before deleting its storage --
# `rm -rf data/` against a live raft node corrupts the bolt file and can
# leave a process writing after the delete.
for _ in $(seq 1 50); do
  { [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; } && { sleep 0.2; continue; }
  curl -sf -o /dev/null "http://${LISTEN}/v1/sys/health?sealedcode=200&uninitcode=200" || break
  sleep 0.2
done

# Keep snapshots/. Everything else is regenerated by bootstrap-openbao.sh --
# including the static-seal key (a fresh raft store needs a fresh key; the
# old one seals nothing recoverable) and the root/recovery tokens.
rm -rf "$STATE_DIR/data"
rm -f "$STATE_DIR"/{openbao.hcl,seal.key,root.token,recovery.key} \
  "$STATE_DIR"/{tofu.tfstate,tofu.tfstate.backup,bao.pid,bao.log}

echo "Cleared. Run: mise run local:openbao:bootstrap"
