// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// The cv_frontend module needs no non-image defaults beyond the schema's
// own — `image` defaults live in `images.cue`, everything else in
// `templates/config.cue`.
values: {}
