#!/usr/bin/env bash
set -euo pipefail

# One-time, per-MACHINE teardown: the inverse of bootstrap-openbao.sh.
# Stops + unregisters the machine-global pitchfork daemon, wipes the raft
# store / rendered config / tofu state, and clears the OS-keychain
# secrets -- so a re-bootstrap never leaves one stale relative to another.
# Raft snapshots under <state_dir>/snapshots/ are KEPT (a reset is usually
# the prelude to restoring from one -- T6).
#
# GitOps role: one-time teardown. Not a reconcile-loop step.
#
# This is MACHINE-WIDE: every git worktree shares the one local OpenBao,
# so this wipes it for all of them. Confirm unless TOOLBOX_OPENBAO_RESET_YES=1.
#
# Test seams (bats): TOOLBOX_OPENBAO_STATE_DIR, TOOLBOX_OPENBAO_DAEMON,
# TOOLBOX_OPENBAO_SUPERVISOR (pitchfork|none), TOOLBOX_OPENBAO_KEYCHAIN_SERVICE.

STATE_DIR="${TOOLBOX_OPENBAO_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/toolbox/openbao}"
DAEMON="${TOOLBOX_OPENBAO_DAEMON:-openbao}"
SUPERVISOR="${TOOLBOX_OPENBAO_SUPERVISOR:-pitchfork}"
KEYCHAIN_SERVICE="${TOOLBOX_OPENBAO_KEYCHAIN_SERVICE:-toolbox-openbao}"

if [ "${TOOLBOX_OPENBAO_RESET_YES:-}" != "1" ]; then
  printf 'Wipe the machine-global local OpenBao at %s (all worktrees)? [y/N] ' "$STATE_DIR"
  read -r reply
  case "$reply" in
  y | Y | yes | YES) ;;
  *)
    echo "Aborted."
    exit 0
    ;;
  esac
fi

if [ "$SUPERVISOR" = "none" ]; then
  [ -f "$STATE_DIR/bao.pid" ] && kill "$(cat "$STATE_DIR/bao.pid")" 2>/dev/null || true
  rm -f "$STATE_DIR/bao.pid" "$STATE_DIR/bao.log"
else
  pitchfork stop "global/$DAEMON" 2>/dev/null || true
  pitchfork daemons remove --global "$DAEMON" 2>/dev/null || true
fi

# Keep snapshots/. Everything else the daemon + tofu own is regenerated by
# bootstrap-openbao.sh.
rm -rf "$STATE_DIR/data" "$STATE_DIR/openbao.hcl" \
  "$STATE_DIR/tofu.tfstate" "$STATE_DIR/tofu.tfstate.backup"

# Clear the keychain item DIRECTLY, not via `fnox remove` -- `fnox remove`
# rewrites fnox.toml and strips the committed `[secrets]` declaration
# (same hazard as `pitchfork daemons remove` rewriting pitchfork.toml).
# The declaration is config and must survive a reset; only the value goes.
security delete-generic-password -s "$KEYCHAIN_SERVICE" -a VAULT_TOKEN >/dev/null 2>&1 || true

echo "Cleared. Run: mise run openbao-bootstrap"
